### ISSUE TITLE
tokenManager is null in DefaultDeleteBuilder

### ISSUE THREAD

**Issue by vitalz** [nhl/link-move#116]
ITokenManager tokenManager is missing in constructor that is why this field is null.

`com.nhl.link.move.runtime.task.delete.DefaultDeleteBuilder.DefaultDeleteBuilder(Class<T>, ITargetCayenneService, IKeyAdapterFactory, ITaskService, IPathNormalizer)`

Compare to 
`com.nhl.link.move.runtime.task.createorupdate.DefaultCreateOrUpdateBuilder.DefaultCreateOrUpdateBuilder(Class<T>, ITargetCayenneService, IExtractorService, ITokenManager, IKeyAdapterFactory, IPathNormalizer, ITargetPropertyWriterService)`

This code throws exception:
`deleteTask.run(new TimestampToken(jobName));`

> Exception occurred: 
java.lang.NullPointerException
        at com.nhl.link.move.runtime.task.BaseTask.run(BaseTask.java:42)
        at com.nhl.link.move.runtime.task.BaseTask.run(BaseTask.java:34)

**Comment by atomashpolskiy** [comment]
@vitalz , I guess the reason for this is that sync tokens make little sense in the context of DeleteTask, so it should not be run via this method. I'm not sure what to do with NPE though (the fix would be trivial, but it's not going to really fix anything, but rather just allow method calls that make no sense).

**Comment by vitalz** [comment]
@atomashpolskiy i think it'd be better customers avoid NPE - for instance, fix overrides methods waiting for sync token - if this parameter does not make sense then overrided methods might have final flag

**Comment by atomashpolskiy** [comment]
@vitalz , I see your point. The problem is that with the current design there are two ways of solving this:
1) throw UnsupportedOperationException or something like that
2) ignore SyncToken instance being passed to the method
I agree that UOE would make more sense than NPE. Ignoring the argument is somewhat confusing, but can be better than runtime exception, depending on who you ask.
I personally don't have an opinion on this matter.

**Comment by vitalz** [comment]
@atomashpolskiy From the loophole point of view, DeleteTask should not inherit from BaseTask (that is why it will not inherit these confusing methods), i.e. class hierarchy might be improved something.

**Comment by atomashpolskiy** [comment]
This is a great idea!
