### ISSUE TITLE
JdbcNormalizer for java.time classes

### ISSUE THREAD

**Issue by andrus** [nhl/link-move#117]
We are missing an important aspect of Java 8 support - converting between`java.util.Date` (and `java.sql.Date,Time,Timestamp`) sources and `java.time.LocalDate`, `java.time.LocalTime`, `java.time.LocalDateTime` targets. Need the corresponding JdbcNormalizers to be built.

**Comment by atomashpolskiy** [comment]
Hi @andrus , check it out in master, close at will

**Comment by andrus** [comment]
Looks good. I wonder if we should allow a subset of lossy conversions that are simply rounding to accommodate the target type? Namely Timestamp -> LocalDate and Timestamp -> LocalTime.

**Comment by atomashpolskiy** [comment]
In fact I started by implementing them, and then after giving it a bit more thought removed them. My reasoning is that we should not be truncating meaningful data...

**Comment by atomashpolskiy** [comment]
But with Timestamp it might make some sense indeed

**Comment by atomashpolskiy** [comment]
Updated

**Comment by andrus** [comment]
Thanks, just put this code in my project. Works great.
