### ISSUE TITLE
String normalizer

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-move#123]
I noticed that we don't have a JdbcNormalizer for java.lang.String. This can lead to quasi-updates when source has a different type. @andrus , do you agree that it would be nice to add a StringNormalizer for java.lang types?

**Comment by andrus** [comment]
I think it is ok. But do we have specific examples of source mappings that would be problematic?

**Comment by atomashpolskiy** [comment]
My concern was about Cayenne thinking that the data changed, while in fact it just had a different data type. I assume that by problematic you mean something that is not going to be converted by the database? In such case, only byte[] comes to mind...

**Comment by andrus** [comment]
ah, good point. I guess it is needed then.

**Comment by atomashpolskiy** [comment]
Added normalization for all standard integral numeric types.
