### ISSUE TITLE
Extend LmRuntimeBuilder API with extractorModelsRoot(URI) 

### ISSUE THREAD

**Issue by ebondareva** [nhl/link-move#133]
To fix [bootique-linkmove #5](https://github.com/bootique/bootique-linkmove/issues/5) the 'extractorsDir' has been replaced with FolderResourceFactory 
but a new issue has arisen: extracotrs xmls on classpath aren't available from a jar.
Suppose, it would be a solution to extend API of `LmRuntimeBuilder` with `extractorModelsRoot(URI)` to take the right `IExtractorModelLoader` in relation to protocol 'classpath:' or 'file:'  
(see `LmRuntimeBuilder.bindModelLoader(...)`).

**Comment by andrus** [comment]
Also see #101. Perhaps that's our solution here.

**Comment by andrus** [comment]
Fixed per #101. I will test with Bootique shortly.
