### ISSUE TITLE
The use of String.replace(..) in PathNormalizer causes massive Pattern creation 

### ISSUE THREAD

**Issue by andrus** [nhl/link-move#143]
Noticed that `java.util.regex.Pattern` is a created millions of times during a simple LM run. Looks like the culprit is `String.replace(..)` in `PathNormalizer`. We must change that to a cheaper method.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/42668/35978541-14a1f7fa-0cf7-11e8-94c1-1a12e922bfb7.png">

**Comment by rzen** [comment]
Wow. Nice catch and fix. Kudos.
