### ISSUE TITLE
Listener methods not inherited

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-move#151]
`com.nhl.link.move.runtime.task.ListenersBuilder#doStageListener` processes `java.lang.Class#getDeclaredMethods`, which do not include inherited methods. I'd like to know, if this is an intended behavior, and, if not, whether it would be difficult to change it? Thanks!

**Comment by andrus** [comment]
I'd be fine if we include inherited methods. 

Long term though I'd like to do away with annotations , and move to lambda-based stage listeners similar to LinkRest (which is much cleaner and easier to use)

**Comment by andrus** [comment]
Planning to move to lambda-based APIs per #197. So closing this one.
