### ISSUE TITLE
Execution.java toString is reporting incorrect start time

### ISSUE THREAD

**Issue by pjjanak** [nhl/link-move#159]
Looks like this is happening in Execution.java:58. 

`DateFormat format = new SimpleDateFormat("YYYY-mm-dd HH:MM:SS");`

Should be

`DateFormat format = new SimpleDateFormat("YYYY-MM-dd HH:mm:SS");`

**Comment by andrus** [comment]
Done. Also changed "SS" to "ss" (ms vs secs).
