### ISSUE TITLE
Long / Integer values in HashMap keys

### ISSUE THREAD

**Issue by vitalz** [nhl/link-move#35]
There two lines in the com.nhl.link.etl.load.CreateOrUpdateLoader.process(List<Map<String, Object>>) method:

			Object key = mapper.keyForTarget(t);
			Map<String, Object> src = mutableSrcMap.remove(key);

Cayenne entity has integer fields when external data source responds according long value in the SQL query result set. Then hash codes for both maps are the same but they do not equal because of type difference that is why java.util.Map.remove(Object) responds null object. I.e., example:

Object key is HashMap:
{String: "a", Integer: "1"}
{String: "b", Integer: "2"}
{String: "c", Integer: "3"}

When mutableSrcMap contains key what is next HashMap:

{String: "a", Long: "1"}
{String: "b", Integer: "2"}
{String: "c", Integer: "3"}

It throws EtlRuntimeException with message like "Invalid key: ..." though the key looks right and there is no duplicates in the database.

**Comment by andrus** [comment]
BTW, found a workaround - a listener with @AfterSourceRowsConverted annotated method can manually fix the data type in 'sources' collection of CreateOrUpdateSegment segment.

**Comment by rzen** [comment]
public class LongToIntListener {
		private static final String PROP_NAME = "longProperty";
	
		@AfterSourceRowsConverted
		public void afterStageFinished(Execution execution, CreateOrUpdateSegment<?> segment) {
			List<Map<String, Object>> sources = segment.getSources();
			for (Map<String, Object> source : sources) {
				if (source.containsKey(PROP_NAME)) {
					source.put(PROP_NAME, ((Long) source.get(PROP_NAME)).intValue());
				}
			}
		}
	}

**Comment by atomashpolskiy** [comment]
@andrus, please see my update. I tried not to do much renaming so that it's clear what changed. Looking forward for your comments/objections.

**Comment by andrus** [comment]
From checking the patch, looks good to me. Let's write some tests for it though that would hit a few conversions.

**Comment by atomashpolskiy** [comment]
Added tests for create/update and delete. Seems to work as intended.
