### ISSUE TITLE
Support for non printable delimiter characters in CSV extractor

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-move#56]
It should be possible to specify hexadecimal code of delimiter character in extractor configuration (using 0x literal). Since all configuration values are encoded as Strings, it should be enough to modify com.nhl.link.etl.runtime.file.csv.CsvRowReader.setDelimiter method to interpret values starting with 0x as character codes (currently it will fail because of restriction on string being exactly 1 character long).

**Comment by andrus** [comment]
+1.
