### ISSUE TITLE
JSON extractor

### ISSUE THREAD

**Issue by rzen** [nhl/link-move#75]
We have an imminent, not super urgent (before summer, hopefully sooner) need for a JSON extractor.

I'm sure once we have it available it'll find many more uses.

**Comment by andrus** [comment]
We should be able to build something similar to the [XMLExtractor](https://github.com/nhl/link-move/tree/4e013615fc8468567371714c4c1aab289d73ddd2/src/main/java/com/nhl/link/move/runtime/xml). @atomashpolskiy , perhaps you can look into this one when you have time?

**Comment by atomashpolskiy** [comment]
Sure. I recall that there were some issues with JSON query languages, so the most important question would be what to use. Several options come to mind: JSON Path 3-rd party implementation, JSON Pointers (though it's very limited) and JS scripts (functions).

**Comment by atomashpolskiy** [comment]
I ended up writing a simple custom parser :) Hope that's not a problem.

**Comment by andrus** [comment]
Cool. Let's document it somewhere though.

**Comment by atomashpolskiy** [comment]
It's [JSONPath](http://goessner.net/articles/JsonPath/), but currently without:
- predicate filters
- ECMAScript 4 array slice syntax

I can add information in wiki or project readme file, if you want me to.

**Comment by andrus** [comment]
Yeah, let's commit this. 

This also reminded me of something I thought before about managing connector dependencies. So I just logged #76
