### ISSUE TITLE
Split link-move into a multi-module Maven project, with specialized extractors in submodules

### ISSUE THREAD

**Issue by andrus** [nhl/link-move#78]
Let's implement better modularization and dependency handling in LinkMove. I suggest the following refactoring of the current project:

```
1. Common parent:
link-move/ -> com.nhl.link.move:link-move-parent

2. Essentially current link-move main module, with new parent and sans some extractors
link-move/link-move/ -> com.nhl.link.move:link-move 

3. A module for the new JSON extractor
link-move/link-move-json/ -> com.nhl.link.move:link-move-json 
```
Extractors can be added to LinkMove runtime dynamically via ServiceLoader API: https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html (used this in Bootique, very powerful and easy to use.. All the users need to do is declare the right set of Maven artifacts in their pom).

Splitting JSON extractor allows us to eliminate hard dependency on Jackson library in default LinkMove. So that's a no-brainier. Now the question is whether we need to split the remaining extractors (XML, CSV, JDBC). They don't introduce any extra dependencies (they all depend on JDK + Cayenne, and Cayenne is needed for LinkMove targets anyways). Still doing a split makes things "symmetrical" and clean (e.g. someone might provide a JDBC extractor that is not Cayenne based or something), so maybe we go with full split and 4 total extractor modules.

**Comment by atomashpolskiy** [comment]
@andrus, one obstacle to using ServiceLoader is that extractor factories need IConnectorService from DI container. So, as I see it, in the most straight-forward solution we'll have something like this:
```java
interface IExtractorFactoryProvider {
  Collection<Class<? extends IExtractorFactory>> getExtractorFactoryTypes();
}
```
and ServiceLoader<IExtractorFactoryProvider> that will add results of getExtractorFactoryTypes() into DI.

This seems like a hack, actually. My understanding is that provider must provide an already constructed instance and not a type. But if I'm correct it's the only way to accomplish what you're saying without DI module providers (like in BQ).

Maybe just require the user to add extractors via LmRuntimeBuilder?

**Comment by aadrian** [comment]
Why not just use Gradle? It's multi-module support is much simpler, and it still can publish all the required artifacts to maven repos.

**Comment by andrus** [comment]
@aadrian there's nothing wrong with Maven multi-module support. Having said that Gradle is great, but that's a different topic.
