### ISSUE TITLE
JsonExtractor should treat attribute's source name as JsonPath expression

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-move#87]
Same as #86 but for JSON extractors. The problem is that [JsonPath](http://goessner.net/articles/JsonPath/) does not define the **access to node's parent node** operation . Thankfully we have a custom implementation, which allows us to extend the "standard" specification.

Thus said, we need to introduce an operator to access node's parent node and invent the syntax to use it in JsonPath queries. Preferably this should be some simple non-literal character sequence or a single non-literal character. Note that `..` (similar operator in XPath) is already used in JsonPath by _recursive descent_ operator (see more [in LM docs](https://github.com/nhl/link-move/tree/master/link-move-json).

@andrus , @dkoyro , @rzen , @vitalz, I think it would be fun to vote :8ball:

**Comment by atomashpolskiy** [comment]
@andrus , @dkoyro , @rzen , @vitalz, guys? I really need your ideas how to name this operator :)

**Comment by andrus** [comment]
What I am wondering before we go about extending the "spec" is the motivation of the spec authors to exclude ability to traverse the parents. Maybe we implement it without the parent access feature for now, and in the meantime ask this question on the JsonPath forum?

**Comment by atomashpolskiy** [comment]
There isn't any "official" forum for this stuff.

**Comment by andrus** [comment]
[Java implementation](https://github.com/jayway/JsonPath) seems to have a [forum](https://groups.google.com/forum/#!forum/jsonpath).

**Comment by atomashpolskiy** [comment]
Yeah, I've seen that. See [older](https://groups.google.com/forum/#!searchin/jsonpath/parent/jsonpath/HnI38s61RxQ/29vverIt9ggJ) and [newer](https://groups.google.com/forum/#!searchin/jsonpath/parent/jsonpath/eMNDMzrL4ik/NR6fMXofM2IJ) questions.

**Comment by atomashpolskiy** [comment]
So far there were two main proposals:
1) Override the "spec" and use `..` for parent access and `...` for recursive descent
2) Use `...` for parent access

The former is really not an option, because parent access can be (and usually is) followed by a child access (`.`). Parent access followed by a child access yields `...`, which creates an ambiguity with the recursive descent. E.g. for the query `$.store...book` it is ambiguous whether to search for all `book`s inside the `store` or get the `book` property of `store`'s parent (the root node).

Using `...` for parent access together with a greedy parser solves this problem, but consecutive parent access looks really nasty. E.g. `$.store.book.......store.book` is a totally valid and unambiguous query, but barely readable.

Thus said, I think we'll move this particular task to a separate issue.
