### ISSUE TITLE
Implement parent access in JsonPath

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-move#89]
See details in #87

**Comment by andrus** [comment]
We haven't discussed nesting of parents. Your point about ....... being unreadable is taken. Clearly a separator of sort is needed. "/" ?

**Comment by atomashpolskiy** [comment]
I'd prefer to hold on to the commonly adopted JsonPath syntax, so that queries that do not use parent access were still valid JsonPath queries. Actually I'm thinking of introducing a kind of "meta-properties", that will be allowed in the same context where a child/property access is allowed. Like this:
`$.store.books#length`
`$.store#parent.store`

**Comment by andrus** [comment]
meta properties may end up being cleaner indeed.

**Comment by atomashpolskiy** [comment]
Guess what? [How to find parent Json node while parsing a JSON](http://stackoverflow.com/questions/20881154/how-to-find-parent-json-node-while-parsing-a-json)
