### ISSUE TITLE
similar decimal values cause db update

### ISSUE THREAD

**Issue by vitalz** [nhl/link-move#91]
LinkMove 6. For instance, source MySQL database responds column 'VALUE':
Type - Decimal
Display size - 10
Precision - 2
Scale - 6

Local database has column 'VALUE' DECIMAL(10, 9). Though value doesn't change in time and it looks quite transportable to target ETL updates local database. For example, it is '0.687500' in source  and the one is '0.687500000' in target.

**Comment by atomashpolskiy** [comment]
@vitalz , your guess is right, `java.math.BigDecimal.equals(Object)` takes scale into consideration. In your example, source has scale of 6 digits whereas target has scale of 9. There is a separate method that ignores difference in scale if values are arithmetically equal, see [JavaDoc](http://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#compareTo-java.math.BigDecimal-). The problem is that, while we could in theory somehow use it to compare source and target keys that involve BigDecimals, I'm afraid we can't influence the internal Cayenne change management for the ordinary attributes.

**Comment by rzen** [comment]
I think the point here is, if target can safely accept the value from source, it should, and it should ignore the difference in type as long as type can be safely converted. 

For example a value of type `INT(1)` would map to `Boolean` without risk of data loss. As such at merge time comparison should ignore type difference and consider `0` equal to `false` and `1` to `true`.

Comparison at merge time is done by LM, that happens outside of Cayenne.

**Comment by atomashpolskiy** [comment]
@vitalz , can you test this [experimental branch](https://github.com/atomashpolskiy/link-etl/tree/merge-decimal-values) with your case?

**Comment by atomashpolskiy** [comment]
> I think the point here is, if target can safely accept the value from source, it should, and it should ignore the difference in type as long as type can be safely converted.

> For example a value of type INT(1) would map to Boolean without risk of data loss. As such at merge time comparison should ignore type difference and consider 0 equal to false and 1 to true.

Obviously someone should come up with a list of such **type coercion** rules. Because there can be different view points on what is equivalent to what _by default_. Or is your primary concern to just emulate Cayenne's change management to get rid of pseudo-updates?

**Comment by rzen** [comment]
> get rid of pseudo-updates

exactly this, whensoever it is safe to do so.

**Comment by atomashpolskiy** [comment]
@rzen, can you elaborate more on the notion of "safe", please? E.g. Date -> DateTime is safe?

**Comment by rzen** [comment]
What we're after is exactly what you said, avoid unnecessary updates.

In other words we want to do something _like_ this:

```java
public class TargetAttributePropertyWriter implements TargetPropertyWriter {
	//...
	@Override
	public boolean write(DataObject target, Object value) {
		Object oldValue = property.readProperty(target);
		property.writeProperty(target, oldValue, value);
		Object newValue = property.readProperty(target);

		return !Util.nullSafeEquals(oldValue, newValue);
	}
}
```

**Comment by vitalz** [comment]
@atomashpolskiy  yes, checked out experimental branch seemed working with no useless updates

**Comment by atomashpolskiy** [comment]
@rzen , it doesn't work that way. `value` and `newValue` are going to be the same object.

**Comment by atomashpolskiy** [comment]
@rzen , me and @vitalz just checked that Cayenne by itself also uses some kind of `equals` to detect changes. Hence it does perform SQL updates event if the only difference is the decimal's scale. Which means that my prior question:

> [should we] just emulate Cayenne's change management?

is irrelevant to this issue, because Cayenne does not handle this case either.

**Comment by atomashpolskiy** [comment]
To keep things simple, for now I'll just use `compareTo` instead of `equals` for numbers.

**Comment by rzen** [comment]
Yea bad example.

Point i was trying to make is, as long as value that would get persisted after writing new value is equal to the original old value, no update is necessary.

**Comment by atomashpolskiy** [comment]
@rzen , I think you are confusing "equal" and "equivalent".

**Comment by rzen** [comment]
Thanks for the correction.

**Comment by rzen** [comment]
Does this account for booleans?

**Comment by atomashpolskiy** [comment]
@rzen , nope, decimals only.

**Comment by rzen** [comment]
Can you please add booleans to this fix?

**Comment by atomashpolskiy** [comment]
@rzen , we don't know if source is INT(1) or INT at all (might be non-JDBC source). All that we know is that source is a number. And I personally don't think that implicitly converting numbers to booleans is a great default. I'd say one should use SQL `CAST`, Cayenne's `#result` or maybe a `StageListener` for such transformations.

**Comment by rzen** [comment]
as long as the target is known to be boolean if source is `1` or `0` and target is `true` or `false` respectively i see no reason to make an update.
