### ISSUE TITLE
Do not create TargetToOnePropertyWriter for the master side of a to-one relationship

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-move#94]
The problem is that the new **master_entity** being saved is lacking ID, which is not auto-generated according to the Cayenne mapping:
```xml
<db-entity name="master_entity" catalog="hr">
   <db-attribute name="id" type="BIGINT" isPrimaryKey="true" isMandatory="true" length="19"/>
   ...
</db-entity>
```

The question is why the new **master_entity** object ends up without an ID in Link-Move. It turns out that the ID attribute is also used in a to-one relationship **master_entity->related_entity**:
```xml
<db-relationship name="relatedEntity" source="master_entity" target="related_entity" toDependentPK="true" toMany="false">
   <db-attribute-pair source="id" target="master_entity_id"/>
</db-relationship>
```

To not overload you with Link-Move specifics, I'll only say that the current implementation does not support such case. When the values extracted from the source are merged into target, each source attribute maps either into a target's attribute or a to-one relationship, not both. In our case source **db:id** ends up being mapped into **MasterEntity.relatedEntity** relationship, and thus new objects are created without IDs.

~~From the LM side I don't think it would be very hard to fix (`com.nhl.link.move.writer.TargetPropertyWriterFactory` and `com.nhl.link.move.writer.TargetPropertyWriter` are the subjects to be changed). It would require some conceptual changes though -- TargetPropertyWriter should be able to set several properties at once.~~

UPDATE: In fact updating the to-one relationship in the described case will not have any effect. So we can just skip it.

**Comment by atomashpolskiy** [comment]
@andrus , I guess this issue should be renamed after merging PR #96

**Comment by andrus** [comment]
Yes, go ahead
